### PR TITLE
feat: remove SSH server and related config

### PR DESCRIPTION
**Pull request by seagyn**
Not really needed in our context anymore. Also bump Ubuntu.

### CODE REVIEW

**Comment by maclsd** [comment]
updated to Ubuntu 22.04 base image

**Comment by maclsd** [comment]
We should check with platform team and whether we need anything fromr [crisis tools](https://www.brendangregg.com/blog/2024-03-24/linux-crisis-tools.html)

**Comment by seagyn** [comment]
> We should check with platform team and whether we need anything fromr [crisis tools](https://www.brendangregg.com/blog/2024-03-24/linux-crisis-tools.html)

Yeah but let's do that in a different PR

**Comment by maclsd** [comment]
I think we can drop Java (openJDK) from it, and python2 should be replaced with python3.
Also replaced _`netcat`_ package with [ncat](https://nmap.org/ncat), as it has a couple of additional features

We could probably replace _`vim`_ with _`vim-tiny`_
but then would need to set up /etc/alternatives/vim  OR  add a symlink manually in /usr/bin

I think package _`telnet`_ can also go, since `curl` supports telnet protocol, and netcat can also to port connection

I recommend adding _`tcptraceroute`_ in order to use TCP protocol for tracing paths, as many places block UDP, and that would allow checking the actual targeted port.

Should we add `kubectl` ?

**Comment by seagyn** [comment]
> I think we can drop Java (openJDK) from it, and python2 should be replaced with python3. Also replaced _`netcat`_ package with [ncat](https://nmap.org/ncat), as it has a couple of additional features
> 
> We could probably replace _`vim`_ with _`vim-tiny`_ but then would need to set up /etc/alternatives/vim OR add a symlink manually in /usr/bin

I think let's leave vim but go ahead and do the rest and let's merge.

**Comment by maclsd** [comment]
Just FYI size change so far:
```
ubuntu@dockerlxc:~/swiss-army-knife$ docker images
REPOSITORY                        TAG         IMAGE ID       CREATED         SIZE
size-check                        latest      1829b83f85d6   6 minutes ago   312MB
quay.io/maclsd/swiss-army-knife   20240304a   95154827991d   4 weeks ago     342MB
```

**Pull request merged**
